### ISSUE TITLE
mcgoftest error

### ISSUE THREAD

**Issue by cfholbert** [genomaths/usefr#1]
Tried running the first example for the mcgoftest function and get the following error:

Error in (function (classes, fdef, mtable) : 
  unable to find an inherited method for function ‘mcgoftest’ for signature ‘"numeric"’

**Comment by genomaths** [comment]
Dear @cfholbert 

Thank you for letting me know.

I have fixed it and all the examples run now (at least from my side).
Please, do not hesitate to contact me if you detect any other issue.

Best,
Robersy
